on:
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4.1.7
            
            - name: Node
              uses: actions/setup-node@v4.0.2
            
            - name: Dependencies
              run: npm ci
            
            - name: Run Build
              run: npm run build

            - name: Configure Pages
              uses: actions/configure-pages@v5
            
            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                # Upload entire repository
                path: './dist'
            
            - name: Deploy Pages
              uses: actions/deploy-pages@v4
