on:
    workflow_dispatch:
    push: 
        branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
        environment:
          name: github-pages
          
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4.1.7
    
            - name: PNPM setup
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Node
              uses: actions/setup-node@v4.0.2
            
            - name: Dependencies
              run: pnpm install
            
            - name: Run Build
              run: pnpm build

            - name: Configure Pages
              uses: actions/configure-pages@v5
            
            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                # Upload entire repository
                path: './dist'
            
            - name: Deploy Pages
              uses: actions/deploy-pages@v4
